# Generated by Django 4.1.3 on 2022-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBazar_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
