# Generated by Django 4.1.3 on 2022-11-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigBazar_App', '0003_categorydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Image',
            new_name='CategoryImage',
        ),
    ]
