# Generated by Django 4.1.3 on 2022-11-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigBazar_App', '0005_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Description',
            new_name='Product_Description',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductImage',
            new_name='Product_Image',
        ),
    ]
