# Generated by Django 4.1.3 on 2022-12-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigBazar_App', '0007_logindb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logindb',
        ),
    ]
