# Generated by Django 4.1.3 on 2022-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(blank=True, max_length=50, null=True)),
                ('CEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('CPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('CConfirm', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
