# Generated by Django 4.1.3 on 2022-12-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigBazar_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetailsdb',
            old_name='CName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customerdetailsdb',
            old_name='CPassword',
            new_name='username',
        ),
    ]
